service: aws-node-express-dynamodb-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

package:
  excludeDevDependencies: true
  exclude:
    - node_modules/**
    - .git/**

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline